/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package humanresource;

/**
 *
 * @author jackline
 */
public class FrameHumanResource extends javax.swing.JFrame {

    FrameEmployeeDetails frameEmployeeDetails;
    
    public FrameHumanResource() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuEmployees = new javax.swing.JMenu();
        menuItemEmployeeDetails = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Human Resource Mangement");
        setBackground(new java.awt.Color(245, 247, 247));
        setLocationByPlatform(true);

        jDesktopPane1.setBackground(new java.awt.Color(13, 57, 55));
        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        menuEmployees.setText("Employees");

        menuItemEmployeeDetails.setText("Employee Details");
        menuItemEmployeeDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemEmployeeDetailsActionPerformed(evt);
            }
        });
        menuEmployees.add(menuItemEmployeeDetails);

        jMenuBar1.add(menuEmployees);

        jMenu2.setText("Departments");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Managers");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("Languages");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("Employee Languages");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Leave Type");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Status");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Leave Application");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemEmployeeDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemEmployeeDetailsActionPerformed

        if( frameEmployeeDetails== null || frameEmployeeDetails.isClosed()){
            frameEmployeeDetails = new  FrameEmployeeDetails ();
            jDesktopPane1.add(frameEmployeeDetails);
            frameEmployeeDetails.setVisible(true);
        }
        else{
            frameEmployeeDetails.setLocation(this.getWidth()/2 -frameEmployeeDetails.getWidth()/2,this.getHeight()/2 -frameEmployeeDetails.getHeight()/2);
            frameEmployeeDetails.setVisible(true);
        }
    }//GEN-LAST:event_menuItemEmployeeDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameHumanResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameHumanResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameHumanResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameHumanResource.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameHumanResource().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuEmployees;
    private javax.swing.JMenuItem menuItemEmployeeDetails;
    // End of variables declaration//GEN-END:variables
}
