/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package humanresource;

import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author jackline
 */
public class FrameEmployeeDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameEmployeeDetails
     */
    public FrameEmployeeDetails() {
        initComponents();
        populateTableEmployeesData();
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmployeeDetails = new javax.swing.JTable();
        labelID = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        labelPhoneNumber = new javax.swing.JLabel();
        labelAddress = new javax.swing.JLabel();
        labelDepartmentName = new javax.swing.JLabel();
        labelDateOfEmployement = new javax.swing.JLabel();
        textFieldID = new javax.swing.JTextField();
        textFieldName = new javax.swing.JTextField();
        textFieldPhoneNumber = new javax.swing.JTextField();
        textFieldAddress = new javax.swing.JTextField();
        comboBoxDepartmentName = new javax.swing.JComboBox<>();
        dateChooserDateOfEmployement = new com.toedter.calendar.JDateChooser();
        buttonUpdate = new javax.swing.JButton();
        buttonInsert = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Employee Details");

        tableEmployeeDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Phone Number", "Address", "Department Code ", "Date Of Employement"
            }
        ));
        jScrollPane1.setViewportView(tableEmployeeDetails);

        labelID.setText("ID");

        labelName.setText("Name");

        labelPhoneNumber.setText("Phone Number");

        labelAddress.setText("Address");

        labelDepartmentName.setText("Department Name");

        labelDateOfEmployement.setText("Date Of Employement");

        comboBoxDepartmentName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxDepartmentNameItemStateChanged(evt);
            }
        });

        buttonUpdate.setText("Update");

        buttonInsert.setText("Insert");
        buttonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertActionPerformed(evt);
            }
        });

        buttonDelete.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDepartmentName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDateOfEmployement, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelID, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelName, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldID)
                            .addComponent(textFieldName)
                            .addComponent(textFieldPhoneNumber)
                            .addComponent(textFieldAddress)
                            .addComponent(comboBoxDepartmentName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateChooserDateOfEmployement, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(buttonUpdate)
                        .addGap(59, 59, 59)
                        .addComponent(buttonInsert)
                        .addGap(54, 54, 54)
                        .addComponent(buttonDelete)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(textFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPhoneNumber)
                    .addComponent(textFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddress)
                    .addComponent(textFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDepartmentName)
                    .addComponent(comboBoxDepartmentName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDateOfEmployement)
                    .addComponent(dateChooserDateOfEmployement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonInsert)
                        .addComponent(buttonUpdate))
                    .addComponent(buttonDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertActionPerformed
        try{
            Class.forName("org.sqlite.JDBC");

            String url = "jdbc:sqlite:/home/jackline/Adhiambo/qlynn.db";            
            Connection conn = DriverManager.getConnection(url);

            String sql = "INSERT INTO Employees VALUES (?, ?, ?, ?, ?, ?)"; 
            PreparedStatement pst = conn.prepareStatement(sql); 

            pst.setInt(1, Integer.parseInt(textFieldID.getText()));
            pst.setString(2, textFieldName.getText());
            pst.setInt(3, Integer.parseInt(textFieldPhoneNumber.getText()));
            pst.setString(4, textFieldAddress.getText());
            pst.setString(5, (String) comboBoxDepartmentName.getSelectedItem());
            SimpleDateFormat sdf = new SimpleDateFormat ("yyyy-MM-dd");
            String date = sdf.format(dateChooserDateOfEmployement.getDate());
            pst.setString(6,date);
            pst.executeUpdate();             
            JOptionPane.showMessageDialog(null, "Insertion successful");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        populateTableEmployeesData();
    }//GEN-LAST:event_buttonInsertActionPerformed

    private void comboBoxDepartmentNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxDepartmentNameItemStateChanged
        try{
            Class.forName("org.sqlite.JDBC");
            String url = "jdbc:sqlite:/home/jackline/Adhiambo/qlynn.db";
            Connection conn = DriverManager.getConnection(url);
            String sql = "SELECT Name FROM Departments"; 
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
        if(evt.getStateChange()== ItemEvent.SELECTED){
            JOptionPane.showMessageDialog(null,comboBoxDepartmentName.getSelectedItem().toString()+
                    " is Selected");
        }
    }//GEN-LAST:event_comboBoxDepartmentNameItemStateChanged
    
    private void populateComboBox(){
        try{
            Class.forName("org.sqlite.JDBC");

            String url = "jdbc:sqlite:/home/jackline/Adhiambo/qlynn.db";            
            Connection conn = DriverManager.getConnection(url);
            String sql= "SELECT Name FROM Departments";
            PreparedStatement pst = conn.prepareStatement(sql); 
            ResultSet rs= pst.executeQuery();
            
            while(rs.next()){
                String name= rs.getString("Name");
                comboBoxDepartmentName.addItem(name);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }    
    
    public void populateTableEmployeesData(){
        
        try{
            Class.forName("org.sqlite.JDBC");
            
            String url = "jdbc:sqlite:/home/jackline/Adhiambo/qlynn.db";
            Connection conn = DriverManager.getConnection(url);
            
            String sql = "SELECT Employees.ID, Employees.Name, Employees.PhoneNumber,"
                    + " Employees.Address, Departments.Name, Employees.DateOfEmployement FROM Employees "
                    + "inner join Departments on Employees.DepartmentCode = Departments.Code;";
            PreparedStatement pst = conn.prepareStatement(sql);
            
            ResultSet rs = pst.executeQuery();
            tableEmployeeDetails.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch (ClassNotFoundException | SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonInsert;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JComboBox<String> comboBoxDepartmentName;
    private com.toedter.calendar.JDateChooser dateChooserDateOfEmployement;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAddress;
    private javax.swing.JLabel labelDateOfEmployement;
    private javax.swing.JLabel labelDepartmentName;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPhoneNumber;
    private javax.swing.JTable tableEmployeeDetails;
    private javax.swing.JTextField textFieldAddress;
    private javax.swing.JTextField textFieldID;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
